project_id = "zivkmpyvfxudzypqezhu"

[functions.delete-test-data]
verify_jwt = true

[functions.harbor-chat]
verify_jwt = true

[functions.index-document]
verify_jwt = true

[functions.regenerate-role-users]
verify_jwt = true

[functions.migrate-storage-files]
verify_jwt = true
